database:
  host: localhost
  port: 3306
  username: username
  password: leaveblankfornone
  database: suggestions
  thread-pool-size: 5

suggestion-categories:
  some:
    name: Some Categpry
    description: This is a category for suggestions
